"""The relational model (sdd.md §5).

What lives here and what does not is ADR-05: Postgres holds *metadata and results*
— instruments, strategies, backtest runs, trades. It does not hold OHLCV. Years of
candles across dozens of symbols are a columnar problem, and they live in Parquet,
catalogued by the `datasets` table below.

Three rules run through every table:

* **Money is `NUMERIC`, never `float`** — see `base.py`.
* **Every timestamp is `TIMESTAMPTZ`** — a candle at "09:00" is meaningless without
  an offset, and a backtest that shifts by an hour when the server changes timezone
  is not a backtest.
* **The database enforces what it can.** A rule that only exists in Python is a rule
  the next maintenance script breaks. If a constraint is expressible in SQL, it is
  expressed in SQL — and there is a test that proves the constraint bites.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Interval,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from tradeforge_db.base import MONEY, PRICE, RATIO, VOLUME, Base
from tradeforge_engine.domain import AssetClass, Side
from tradeforge_schema.models import TIMEFRAMES

# --------------------------------------------------------------------------- #
# Enumerations                                                                  #
# --------------------------------------------------------------------------- #
# Stored as VARCHAR + CHECK (`native_enum=False`), not as a Postgres ENUM type.
# A native enum is a schema object: adding `crypto` to it means ALTER TYPE, and
# *removing* a value is not supported at all — you rebuild the type and rewrite
# every column that uses it. A CHECK constraint is dropped and recreated in three
# lines, which is what makes these migrations honestly reversible. The cost is a
# few bytes per row over an enum's four; at this scale, nothing.


class BacktestStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"


class SelectionMetric(StrEnum):
    """What a walk-forward fold maximises when it picks a winner from its training grid.

    An enum rather than a free string because this is the one input that decides what the
    whole experiment *means*. "The best parameters" is not a fact about a grid; it is a fact
    about a grid **and a ranking**, and a walk-forward that could not say which ranking it
    used would report an out-of-sample number nobody could reproduce.

    All four name a column on `BacktestMetrics`, and three of them are nullable there —
    which is the reason `walkforward.choose` refuses to treat a null as a zero. Sharpe over
    zero trades is undefined, not flat.
    """

    NET_PROFIT = "net_profit"
    PROFIT_FACTOR = "profit_factor"
    SHARPE = "sharpe"
    EXPECTANCY = "expectancy"


class ExitReason(StrEnum):
    STOP_LOSS = "sl"
    TAKE_PROFIT = "tp"
    CONDITION = "condition"
    KILL = "kill"
    MANUAL = "manual"


def _enum(enum_type: type[StrEnum], name: str) -> Enum:
    # Two defaults here are traps, and both would have shipped silently.
    #
    # `create_constraint=True` is not the default in SQLAlchemy 2.0. Leave it off and
    # the column is a bare VARCHAR: any string at all gets in, and the enum exists only
    # in Python — precisely the "rule that lives in one place" failure this module is
    # written to avoid.
    #
    # `values_callable` is what makes the database store `'sl'` rather than
    # `'STOP_LOSS'`. By default SQLAlchemy persists the member *name*, not its value —
    # so the DSL, the API's JSON and the database would each spell the same exit reason
    # differently, and every query against a literal would quietly match nothing.
    return Enum(
        enum_type,
        name=name,
        native_enum=False,
        create_constraint=True,
        values_callable=lambda members: [member.value for member in members],
        length=16,
        validate_strings=True,
    )


# The set of legal timeframes is owned by the DSL, not by the database.
TIMEFRAME = String(4)
_TIMEFRAME_VALUES = ", ".join(f"'{tf}'" for tf in TIMEFRAMES)


def _timeframe_check() -> CheckConstraint:
    # The naming convention prefixes the table, so the same bare name yields
    # `ck_datasets_timeframe` and `ck_backtests_timeframe`.
    return CheckConstraint(f"timeframe IN ({_TIMEFRAME_VALUES})", name="timeframe")


def _uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID primary key, generated by the application.

    Used for everything the API addresses by id. Sequential integers would leak
    volume (`/backtests/1041` tells a competitor how many runs exist) and would
    force a round-trip to the database before a client can reference the row it is
    about to create. `trades` is the deliberate exception — see below.
    """
    return mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


def _created_at() -> Mapped[dt.datetime]:
    # server_default, not a Python default: the database's clock is the one clock
    # every writer shares, whatever timezone the machine that inserted thinks it is in.
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


# --------------------------------------------------------------------------- #
# Instruments — what can be traded                                              #
# --------------------------------------------------------------------------- #


class Instrument(Base):
    """A tradable symbol and the numbers needed to price a position in it.

    `tick_size`, `tick_value` and `contract_size` are not decoration: they are how
    the engine converts a price move into money, and they differ by asset class.
    One tick of EURUSD on a standard lot is worth $1; one tick of AAPL is worth one
    cent per share. Get these wrong and every P&L in the system is wrong by a
    constant factor — which is exactly the kind of bug that looks like a great
    strategy. Populated for real by the collector from MT5 `symbol_info` (PR-102).
    """

    __tablename__ = "instruments"

    id: Mapped[uuid.UUID] = _uuid_pk()

    symbol: Mapped[str] = mapped_column(String(32), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    asset_class: Mapped[AssetClass] = mapped_column(
        _enum(AssetClass, "asset_class"), nullable=False
    )
    exchange: Mapped[str | None] = mapped_column(String(64))

    # Forex has a base and a quote currency (EUR/USD). A stock has only the currency
    # it settles in, so `currency_base` is nullable and `currency_quote` never is.
    currency_base: Mapped[str | None] = mapped_column(String(8))
    currency_quote: Mapped[str] = mapped_column(String(8), nullable=False)

    tick_size: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    tick_value: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    contract_size: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    digits: Mapped[int] = mapped_column(SmallInteger, nullable=False)

    # The broker's quoted spread, in ticks, as a *default* for a run's cost model — not a
    # number the engine ever reads. Costs are plugged in per backtest (ADR-07), and this is
    # only what the screen offers before anyone overrides it. Kept here, with the other
    # broker-quoted specs, because that is what it is: `symbol_info` said so.
    #
    # Nullable, and the distinction is load-bearing. NULL means *nobody has measured this
    # symbol's spread* — a row seeded by hand, or catalogued before this column existed.
    # Zero would mean "this instrument is free to trade", which is a claim, and the wrong
    # one. The screen falls back to charging nothing only when it can say why.
    #
    # Stored in ticks rather than in MT5 "points" because the engine's `SpreadCostModel`
    # counts ticks, and the two are not the same quantity by definition — see the collector,
    # which converts and refuses when a broker's point and tick disagree in a way it cannot
    # reconcile. Storing the raw MT5 number would leave that conversion to every reader.
    default_spread_points: Mapped[Decimal | None] = mapped_column(PRICE)

    created_at: Mapped[dt.datetime] = _created_at()
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # `passive_deletes="all"`: the database decides what a delete means, not the ORM.
    # By default SQLAlchemy "helpfully" NULLs out the children's foreign key before
    # deleting the parent — which would bypass the RESTRICT entirely if `instrument_id`
    # were nullable, silently orphaning every Parquet file this symbol catalogues. Told
    # to keep its hands off, it emits the DELETE and lets Postgres refuse.
    datasets: Mapped[list[Dataset]] = relationship(
        back_populates="instrument", passive_deletes="all"
    )

    __table_args__ = (
        # Zero or negative here would make position sizing divide by zero or flip
        # the sign of every trade. The database refuses before the engine ever sees it.
        CheckConstraint("tick_size > 0", name="tick_size_positive"),
        CheckConstraint("tick_value > 0", name="tick_value_positive"),
        CheckConstraint("contract_size > 0", name="contract_size_positive"),
        CheckConstraint("digits BETWEEN 0 AND 10", name="digits_range"),
        # Unlike the three above, zero is *allowed*: a broker genuinely can quote a
        # zero spread on some instruments. Negative is not — a spread is a magnitude,
        # and a negative one would credit the account for trading.
        CheckConstraint(
            "default_spread_points IS NULL OR default_spread_points >= 0",
            name="default_spread_points_non_negative",
        ),
    )


# --------------------------------------------------------------------------- #
# Broker symbols — a snapshot of what the account can see today                 #
# --------------------------------------------------------------------------- #


class BrokerSymbol(Base):
    """One line of the broker's own catalogue, as MT5 last reported it.

    ⚠️ **Deliberately not `Instrument`, and the split is the whole point of the table.**
    `Instrument` is what *this system* knows and prices: it carries `tick_value` and
    `contract_size`, it is what a `Backtest` and a `Dataset` point at with `ondelete="RESTRICT"`,
    and a row there means somebody catalogued that symbol on purpose. This is a *photograph of
    an account* — what the broker happens to offer right now, most of it never collected and
    most of it never traded.

    Folding the two together would make switching brokers destructive. The same terminal that
    listed 9550 symbols with AAPL in it now lists 84 of forex and CFDs (measured 19/08/2026,
    after the account changed), and a sync that owned `instruments` would have had to delete
    rows that still have Parquet on disk and backtests pointing at them. Separate, a sync is
    free to replace the whole table, because nothing points at it.

    Not written by the API, which cannot reach MetaTrader at all (ADR-02, and the wheel does
    not exist on Linux). Written by the host agent, read by `/symbols/search`.
    """

    __tablename__ = "broker_symbols"

    id: Mapped[uuid.UUID] = _uuid_pk()

    symbol: Mapped[str] = mapped_column(String(32), nullable=False, unique=True)

    # What the terminal calls it in a human sentence, and where it files it in its tree
    # ("Forex\\Majors\\EURUSD"). The path is how the collector already infers an asset class,
    # so keeping it lets the screen group results without a second round trip to the host.
    description: Mapped[str | None] = mapped_column(String(256))
    path: Mapped[str | None] = mapped_column(String(256))

    digits: Mapped[int | None] = mapped_column(SmallInteger)

    # Whether the symbol is in Market Watch. ⚠️ Kept for display only: measured on this
    # broker, a *hidden* symbol answers `symbols_get(group=...)` and hands over history just
    # like a visible one, so this must never be used to filter search results — it would hide
    # 74 of 84 symbols for no reason. It matters to the live loop, which does have to select a
    # symbol before watching it.
    # ⚠️ Both defaults fire at **write** time, and neither at construction. `default` is what
    # SQLAlchemy sends on an INSERT that omits the column; `server_default` is the DDL that
    # covers a row inserted by anything else. So `BrokerSymbol(symbol="X")` has
    # `visible = None` until it is flushed, which the `Mapped[bool]` annotation does nothing to
    # prevent — a trap only a test that builds rows by hand ever meets, since every row this
    # code reads came back from a NOT NULL column.
    visible: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )

    # ⚠️ Which broker this row came from, on every row rather than in a one-row side table.
    # A sync replaces the whole snapshot inside one transaction, so denormalising cannot drift
    # — and it lets the screen say "84 symbols from MetaQuotes-Demo, synced 5 minutes ago"
    # instead of showing a list with no provenance. A user who switched accounts and forgot is
    # exactly the person a stale list would mislead.
    server: Mapped[str | None] = mapped_column(String(64))
    synced_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        # ⚠️ `varchar_pattern_ops`, because the only query this table answers is a prefix
        # match. Under a non-C collation a plain btree cannot serve `LIKE 'EUR%'` and Postgres
        # falls back to a sequential scan — an index that looks present and does nothing. It
        # would never be noticed either, because at this table's size the scan is fast.
        #
        # Spelled with `postgresql_ops` rather than as a text expression so alembic can compare
        # it: an operator clause inside an expression makes the drift check warn and skip,
        # which is a check that reports green about something it did not look at.
        Index(
            "ix_broker_symbols_symbol_prefix",
            "symbol",
            postgresql_ops={"symbol": "varchar_pattern_ops"},
        ),
    )


# --------------------------------------------------------------------------- #
# Datasets — the catalogue of what exists in Parquet                            #
# --------------------------------------------------------------------------- #


class Dataset(Base):
    """One (instrument, timeframe) coverage record pointing at Parquet on disk.

    The candles are not here; the *knowledge of which candles exist* is. That split
    is ADR-05, and it is what lets a backtest answer "do I have EURUSD H1 for 2021?"
    with an index lookup instead of opening files.

    One row per (instrument, timeframe): a re-run of the backfill updates the row it
    already owns rather than appending a second, contradictory account of the same
    range. That unique constraint is what makes the collector idempotent (PR-102).
    """

    __tablename__ = "datasets"

    id: Mapped[uuid.UUID] = _uuid_pk()

    # RESTRICT, not CASCADE: deleting a symbol must not silently orphan gigabytes of
    # Parquet. Whoever wants the instrument gone deals with its history first.
    instrument_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )
    timeframe: Mapped[str] = mapped_column(TIMEFRAME, nullable=False)

    date_from: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    date_to: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    candle_count: Mapped[int] = mapped_column(Integer, nullable=False)
    parquet_path: Mapped[str] = mapped_column(Text, nullable=False)
    collected_at: Mapped[dt.datetime] = _created_at()

    instrument: Mapped[Instrument] = relationship(back_populates="datasets")

    __table_args__ = (
        UniqueConstraint("instrument_id", "timeframe"),
        _timeframe_check(),
        CheckConstraint("date_to >= date_from", name="date_range"),
        CheckConstraint("candle_count >= 0", name="candle_count_non_negative"),
    )


# --------------------------------------------------------------------------- #
# Strategies — append-only                                                      #
# --------------------------------------------------------------------------- #


class Strategy(Base):
    """A saved strategy. **This table is append-only** (ADR-0010).

    A backtest is a claim about a specific strategy. If the strategy's definition
    can be edited in place, then every result ever produced becomes unexplainable:
    the row the run points at no longer describes the run. So editing is not an
    UPDATE — it is an INSERT of the next version, linked to its parent, and a
    trigger in the migration rejects UPDATE outright.

    `name`, `description` and `schema_version` are *generated columns*: Postgres
    derives them from the JSONB on write. They exist to be indexed and listed
    without parsing JSON, and being generated means they cannot disagree with the
    document they came from. The DSL stays the single source of truth, all the way
    down into the database.
    """

    __tablename__ = "strategies"

    id: Mapped[uuid.UUID] = _uuid_pk()

    # The DSL document, validated by `tradeforge_schema` before it ever gets here.
    definition: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)

    name: Mapped[str] = mapped_column(
        Text, Computed("definition ->> 'name'", persisted=True), nullable=False
    )
    description: Mapped[str | None] = mapped_column(
        Text, Computed("definition ->> 'description'", persisted=True)
    )
    schema_version: Mapped[str] = mapped_column(
        String(16), Computed("definition ->> 'schema_version'", persisted=True), nullable=False
    )

    version: Mapped[int] = mapped_column(Integer, nullable=False)
    parent_version_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("strategies.id", ondelete="RESTRICT")
    )

    created_at: Mapped[dt.datetime] = _created_at()

    parent: Mapped[Strategy | None] = relationship(remote_side="Strategy.id")

    __table_args__ = (
        # Two rows claiming to be "MA Cross v3" would make a backtest's provenance
        # ambiguous, which is the one thing this table exists to prevent.
        UniqueConstraint("name", "version"),
        CheckConstraint("version >= 1", name="version_positive"),
        # A first version has no parent; every later version must have one. Written
        # as an equivalence so both halves are enforced by the one constraint.
        CheckConstraint(
            "(version = 1) = (parent_version_id IS NULL)", name="lineage_starts_at_version_1"
        ),
    )


# --------------------------------------------------------------------------- #
# Backtests                                                                     #
# --------------------------------------------------------------------------- #


class Basket(Base):
    """One strategy launched over several symbols at once, to ask whether it travels.

    A strategy that works on exactly one instrument is a strategy fitted to that
    instrument's history. This table exists so that suspicion has an experiment: same
    strategy, same window, same capital, N markets, results side by side.

    **It groups runs; it is not a run.** Each symbol executes as its own `Backtest`,
    untouched — the engine holds one instrument and one position per run by construction
    (`loop._reject_foreign_symbol`, `Portfolio._open`), and a basket deliberately does not
    challenge that. A shared-capital portfolio, where positions compete for one account,
    is a different product answering a different question, and it would need the engine
    rewritten at its most invariant-heavy point.

    ⚠️ **Consequence worth stating where the data lives:** every run starts with the full
    `initial_capital`, so the runs of a basket cannot be added up. Four runs of $10 000 are
    neither a $10 000 account nor a $40 000 one. What a basket reports is *dispersion*
    across markets, never a combined account curve — see `routers/baskets`.

    No `cost_model` column, and the absence is the design. Each run is charged that
    instrument's own measured spread (PR-226), so the basket has no single cost to store;
    the concrete model lands on each `Backtest` row, which is what keeps each one
    independently reproducible.
    """

    __tablename__ = "baskets"

    id: Mapped[uuid.UUID] = _uuid_pk()

    strategy_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("strategies.id", ondelete="RESTRICT"), nullable=False
    )
    timeframe: Mapped[str] = mapped_column(TIMEFRAME, nullable=False)

    date_from: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    date_to: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    initial_capital: Mapped[Decimal] = mapped_column(MONEY, nullable=False)

    created_at: Mapped[dt.datetime] = _created_at()

    # `passive_deletes="all"`: the FK is ON DELETE SET NULL, and Postgres is the one that
    # should apply it. Left to itself SQLAlchemy would load every run to NULL its column
    # one by one — and, worse, would do so even when the database's rule says otherwise.
    backtests: Mapped[list[Backtest]] = relationship(back_populates="basket", passive_deletes="all")

    __table_args__ = (
        _timeframe_check(),
        CheckConstraint("date_to >= date_from", name="date_range"),
        CheckConstraint("initial_capital > 0", name="initial_capital_positive"),
    )


class Study(Base):
    """One strategy launched over a grid of its own parameters, to see the shape of the result.

    The sibling of `Basket`, and the pair is the point: a basket varies the **market** and
    holds the parameters still; a study varies the **parameters** and holds the market still.
    Both exist because one number from one run cannot tell a method apart from a lucky corner,
    and they attack that from the two directions available.

    **It groups runs; it is not a run.** Each point of the grid executes as its own `Backtest`
    against its own stored `Strategy` — so a run still answers "what did I execute?" by
    pointing at one immutable document, exactly as every other run in the system does. The
    alternative, one strategy plus a per-run override, would put that answer in two places
    joined by merge logic, and nothing would raise the day they disagreed.

    ⚠️ **What this table cannot do, and it is the reason the next PR exists.** A grid finds the
    best point *in the data it searched*. That is not a prediction; it is a description, and
    the wider the grid the more of it is description of noise. Reading the maximum of a
    hundred runs as "the parameters to trade" is the central mistake this whole feature makes
    easy, which is why the read side reports dispersion beside the best point and says the
    best point is in-sample. Walk-forward (PR-204) is what turns a study into evidence: train
    on one window, *test* on the next, and see whether the choice survives being made blind.

    No `cost_model` column, and the absence is deliberate — same as `Basket`. The concrete
    model lands on each `Backtest` row, which is what keeps every point independently
    reproducible. Here the points do share one model by construction, since they are written
    in a single transaction from a single request; storing it twice would create a second
    place for it to be true.
    """

    __tablename__ = "studies"

    id: Mapped[uuid.UUID] = _uuid_pk()

    strategy_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("strategies.id", ondelete="RESTRICT"), nullable=False
    )
    instrument_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )
    timeframe: Mapped[str] = mapped_column(TIMEFRAME, nullable=False)

    date_from: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    date_to: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    initial_capital: Mapped[Decimal] = mapped_column(MONEY, nullable=False)

    grid: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    """The axes as declared: `{"setup.params.period": [5, 9, 20], ...}`, in order.

    Kept because it is **not recoverable from the runs**. Each point's values survive as text
    inside its strategy's name, and reading a heatmap's axes back out of parsed names is the
    kind of reconstruction that works right up until a value contains a comma.
    """

    created_at: Mapped[dt.datetime] = _created_at()

    backtests: Mapped[list[Backtest]] = relationship(back_populates="study", passive_deletes="all")

    __table_args__ = (
        _timeframe_check(),
        CheckConstraint("date_to >= date_from", name="date_range"),
        CheckConstraint("initial_capital > 0", name="initial_capital_positive"),
        # A study that varies nothing is a backtest. Enforced here as well as in the router
        # because a row with an empty grid claims an experiment and describes none.
        CheckConstraint(
            "jsonb_typeof(grid) = 'object' AND grid <> '{}'::jsonb", name="grid_not_empty"
        ),
    )


class Backtest(Base):
    """One run of one strategy version over one instrument and period.

    `engine_version` is stored alongside `strategy_id` on purpose. Reproducing a
    result needs both: the strategy says *what* was decided, the engine version says
    *how* it was executed. A fill-model bugfix six months from now changes the second
    without touching the first, and this column is what stops that from looking like
    the strategy silently got better.
    """

    __tablename__ = "backtests"

    id: Mapped[uuid.UUID] = _uuid_pk()

    # Indexed, because Postgres does not index a foreign key for you — only the referenced
    # side gets one, from its primary key. "Which runs used this strategy?" is what the
    # strategy listing asks to leave out the strategies a grid generated, and without this it
    # is a sequential scan of every run ever made, once per strategy.
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("strategies.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    instrument_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )

    # Nullable, and it stays nullable: a run launched on its own belongs to no basket, which
    # is the truth for every row made before baskets existed and for every single-symbol run
    # made after. Not a gap waiting to be backfilled.
    #
    # SET NULL, not CASCADE. Deleting the grouping must not delete the measurements — "I no
    # longer care about this comparison" is not "destroy four backtests and their trades".
    basket_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("baskets.id", ondelete="SET NULL"), index=True
    )
    basket: Mapped[Basket | None] = relationship(back_populates="backtests")

    # The other grouping, on the same terms. A run belongs to no study unless a grid produced
    # it, and the two columns are independent: a run carrying both would be one point of a
    # grid that was also launched across markets, which is a coherent thing to want rather
    # than a state to forbid.
    study_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("studies.id", ondelete="SET NULL"), index=True
    )
    study: Mapped[Study | None] = relationship(back_populates="backtests")

    timeframe: Mapped[str] = mapped_column(TIMEFRAME, nullable=False)

    date_from: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    date_to: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    initial_capital: Mapped[Decimal] = mapped_column(MONEY, nullable=False)

    # The cost model is a plugged-in component (ADR-07), so its configuration is a
    # document, not a column. Storing it per run is what makes the run reproducible:
    # "the same backtest with a wider spread" must be a different, comparable row.
    cost_model: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)

    status: Mapped[BacktestStatus] = mapped_column(
        _enum(BacktestStatus, "backtest_status"),
        nullable=False,
        default=BacktestStatus.QUEUED,
    )
    error: Mapped[str | None] = mapped_column(Text)
    engine_version: Mapped[str] = mapped_column(String(32), nullable=False)

    created_at: Mapped[dt.datetime] = _created_at()
    started_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))

    # What the run actually ate, as opposed to what it was asked for. `date_from`/`date_to`
    # are a *request*; the dataset underneath may start later or end earlier, and then the
    # run silently covers less ground than its own row claims. Asking for two years and
    # backtesting five months is not a small discrepancy — it is a different experiment,
    # and without these columns nothing in the system can tell the two apart afterwards.
    #
    # Nullable because a run that failed never got as far as reading a candle, and because
    # every row that existed before this column did is honestly unknown, not zero.
    candles_seen: Mapped[int | None] = mapped_column(Integer)
    first_candle: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    last_candle: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))

    # `passive_deletes=True` pairs with ON DELETE CASCADE: Postgres removes the children
    # in one statement. Without it, SQLAlchemy would load every trade of the run into
    # memory just to issue a DELETE per row — a backtest with 40 000 trades would take
    # 40 000 round trips to delete.
    metrics: Mapped[BacktestMetrics | None] = relationship(
        back_populates="backtest", cascade="all, delete-orphan", passive_deletes=True
    )
    trades: Mapped[list[Trade]] = relationship(
        back_populates="backtest", cascade="all, delete-orphan", passive_deletes=True
    )

    __table_args__ = (
        _timeframe_check(),
        CheckConstraint("date_to >= date_from", name="date_range"),
        CheckConstraint("initial_capital > 0", name="initial_capital_positive"),
        # A failed run that does not say why is a support ticket with no answer.
        CheckConstraint("status <> 'failed' OR error IS NOT NULL", name="failed_needs_error"),
        CheckConstraint(
            "finished_at IS NULL OR started_at IS NOT NULL", name="finished_implies_started"
        ),
        CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at", name="finished_after_started"
        ),
        # A run that saw candles must say which ones, and a run that saw none must not
        # claim a range. Half-filled provenance is worse than none: it reads as authoritative.
        CheckConstraint(
            "(candles_seen IS NULL AND first_candle IS NULL AND last_candle IS NULL)"
            " OR (candles_seen > 0 AND first_candle IS NOT NULL AND last_candle IS NOT NULL"
            " AND last_candle >= first_candle)",
            name="candle_provenance_complete",
        ),
        # The worker polls for work by status; without this it seq-scans the table.
        Index("ix_backtests_status_created_at", "status", "created_at"),
    )


class BacktestMetrics(Base):
    """The summary of a finished run (sdd.md §5).

    The sign convention is enforced, not documented: `gross_profit >= 0`,
    `gross_loss <= 0`, and `net_profit` is exactly their sum. Every backtesting
    codebase eventually grows a bug where losses are added instead of subtracted
    because two functions disagreed about whether "loss" meant a negative number or
    a magnitude. Here the database settles it, and `NUMERIC` makes the equality check
    safe — the same CHECK on floats would fail on rounding alone.

    Nullable metrics are nullable for a reason: Sharpe over zero trades is not 0, it
    is undefined, and writing 0 there would quietly rank a strategy that never traded
    alongside one that broke even.
    """

    __tablename__ = "backtest_metrics"

    # PK *is* the FK: exactly one metrics row per backtest, enforced structurally
    # rather than by a unique index bolted on afterwards. CASCADE because metrics are
    # derived data — they have no meaning once the run they summarise is gone.
    backtest_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("backtests.id", ondelete="CASCADE"), primary_key=True
    )

    net_profit: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    gross_profit: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    gross_loss: Mapped[Decimal] = mapped_column(MONEY, nullable=False)

    total_trades: Mapped[int] = mapped_column(Integer, nullable=False)
    long_trades: Mapped[int] = mapped_column(Integer, nullable=False)
    short_trades: Mapped[int] = mapped_column(Integer, nullable=False)

    win_rate: Mapped[Decimal] = mapped_column(RATIO, nullable=False)
    payoff: Mapped[Decimal | None] = mapped_column(RATIO)
    profit_factor: Mapped[Decimal | None] = mapped_column(RATIO)
    expectancy: Mapped[Decimal | None] = mapped_column(MONEY)

    max_drawdown_abs: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    max_drawdown_pct: Mapped[Decimal] = mapped_column(RATIO, nullable=False)
    max_dd_duration_days: Mapped[int] = mapped_column(Integer, nullable=False)

    sharpe: Mapped[Decimal | None] = mapped_column(RATIO)
    sortino: Mapped[Decimal | None] = mapped_column(RATIO)
    cagr: Mapped[Decimal | None] = mapped_column(RATIO)

    avg_trade_duration: Mapped[dt.timedelta | None] = mapped_column(Interval)

    # The equity curve is a time series, read whole and never queried by element —
    # a JSONB array, not ten thousand rows in a table nobody joins against.
    equity_curve: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)

    backtest: Mapped[Backtest] = relationship(back_populates="metrics")

    __table_args__ = (
        CheckConstraint("gross_profit >= 0", name="gross_profit_sign"),
        CheckConstraint("gross_loss <= 0", name="gross_loss_sign"),
        CheckConstraint("net_profit = gross_profit + gross_loss", name="net_profit_balances"),
        CheckConstraint("total_trades = long_trades + short_trades", name="trade_counts_balance"),
        CheckConstraint("total_trades >= 0", name="total_trades_non_negative"),
        CheckConstraint("win_rate BETWEEN 0 AND 1", name="win_rate_is_a_fraction"),
        CheckConstraint("max_drawdown_abs >= 0", name="max_drawdown_abs_non_negative"),
        CheckConstraint("max_drawdown_pct BETWEEN 0 AND 1", name="max_drawdown_pct_is_a_fraction"),
        CheckConstraint("max_dd_duration_days >= 0", name="max_dd_duration_non_negative"),
    )


# --------------------------------------------------------------------------- #
# Trades                                                                        #
# --------------------------------------------------------------------------- #


class Trade(Base):
    """One round trip, with the indicator snapshot that justified the entry.

    `context` is the column this table is really for. It stores what the indicators
    read at the moment of entry, which is what will later answer "does this strategy
    only work when ADX > 25?" — and it is the training material for the phase-3 LLM
    analysis. Recomputing it afterwards would mean re-running the engine and hoping
    nothing changed; capturing it at the entry costs nothing.

    Unlike every other table here, the primary key is a BIGINT, not a UUID. Trades
    are high-volume and are never addressed individually by a client — they are read
    in bulk by `backtest_id`. A sequential key keeps that index compact and its
    inserts append-only at the right edge of the B-tree, which a random UUID does not.

    `backtest_id` is NOT NULL today. Phase 2 adds live sessions and relaxes this into
    "exactly one of backtest_id / live_session_id", which is an honest migration then
    — as opposed to a nullable foreign key now, pointing at a table that does not exist.
    """

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    backtest_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("backtests.id", ondelete="CASCADE"), nullable=False
    )
    instrument_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )

    direction: Mapped[Side] = mapped_column(_enum(Side, "direction"), nullable=False)

    entry_time: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    volume: Mapped[Decimal] = mapped_column(VOLUME, nullable=False)

    # An open position has no exit yet. The CHECKs below keep the four exit columns
    # from ever telling half a story — a trade with an exit price but no exit time is
    # not a trade, it is a bug that would land in the metrics as free money.
    exit_time: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    exit_price: Mapped[Decimal | None] = mapped_column(PRICE)
    exit_reason: Mapped[ExitReason | None] = mapped_column(_enum(ExitReason, "exit_reason"))

    # The stop the trade was **sized against** — the level it opened with, not the one it
    # closed at. A strategy that trails its stop (ADR-0018) exits at a level this column never
    # saw, so `exit_reason = 'sl'` with `exit_price != stop_loss` is correct, not a bug. It is
    # this number that `r_multiple` divides by, and the two have to come from the same stop.
    stop_loss: Mapped[Decimal | None] = mapped_column(PRICE)
    take_profit: Mapped[Decimal | None] = mapped_column(PRICE)

    gross_pnl: Mapped[Decimal | None] = mapped_column(MONEY)
    costs: Mapped[Decimal | None] = mapped_column(MONEY)
    net_pnl: Mapped[Decimal | None] = mapped_column(MONEY)
    r_multiple: Mapped[Decimal | None] = mapped_column(RATIO)

    context: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    # The entry's picture: the bars the strategy had seen when it decided, carried on to the
    # bar that filled the order, plus the rectangles drawn over them. `context` answers "under
    # what numbers did this fire?"; this answers "did it fire where the method says?" — and
    # that one is answered by looking, not by aggregating, which is why it is a time series
    # and lives in its own column rather than as a key `context` readers must learn to skip.
    #
    # Written by the engine at the decision and never recomputed. Rebuilding the window later
    # from the Parquet would mean charting bars that are not necessarily the ones the strategy
    # saw — the file gets recollected, extended, corrected — and the chart would disagree with
    # the trade drawn on it with nothing to show for it. Same argument as `candles_seen`.
    snapshot: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    backtest: Mapped[Backtest] = relationship(back_populates="trades")

    __table_args__ = (
        CheckConstraint("entry_price > 0", name="entry_price_positive"),
        CheckConstraint("exit_price IS NULL OR exit_price > 0", name="exit_price_positive"),
        CheckConstraint("volume > 0", name="volume_positive"),
        # Closed means closed: all four exit columns arrive together or none do.
        CheckConstraint(
            "(exit_time IS NULL) = (exit_price IS NULL)"
            " AND (exit_time IS NULL) = (exit_reason IS NULL)"
            " AND (exit_time IS NULL) = (net_pnl IS NULL)",
            name="exit_is_all_or_nothing",
        ),
        CheckConstraint("exit_time IS NULL OR exit_time >= entry_time", name="exit_after_entry"),
        # Costs are a magnitude, and net is gross minus them. Stating it here means no
        # two call sites can disagree about the sign — the same trap as gross_loss above.
        CheckConstraint("costs IS NULL OR costs >= 0", name="costs_non_negative"),
        CheckConstraint("net_pnl IS NULL OR net_pnl = gross_pnl - costs", name="net_pnl_balances"),
        Index("ix_trades_backtest_id_entry_time", "backtest_id", "entry_time"),
    )


# --------------------------------------------------------------------------- #
# Walk-forward — the experiment that scores a choice it did not get to see      #
# --------------------------------------------------------------------------- #


class WalkForward(Base):
    """A study re-asked honestly: choose the parameters on one window, score them on the next.

    `Study` above ends its own docstring by naming the thing it cannot do, and this is that
    thing. A grid searches and scores on **the same candles**, so its best point is the
    luckiest arrangement of one sample — and the wider the grid, the luckier. That number is a
    description of a past. It is not evidence about a future, and no amount of dispersion
    reported beside it makes it one.

    A walk-forward splits the period into folds. In each fold the entire grid runs over a
    *training* window, one point is chosen by a stated rule, and **that point alone** runs over
    the *test* window that follows it. The test window was not searched, so its result is what
    the method would have returned to somebody making the choice blind. Stitched across folds
    it answers the only question that matters before risking money.

    **It re-runs a study rather than taking a grid of its own**, which is why the sole input
    here is `study_id`. The comparison this table exists to support is *"the heatmap said this,
    the blind choice got that"* — and that comparison is only sound if both used the same grid
    over the same market. Accepting a grid again would let the two drift apart with nothing
    able to notice, since a retyped grid that differs by one value still looks like the same
    experiment.

    ⚠️ **Its own status column, and the reason is that this row can fail on its own.** Every
    other grouping in this schema (`Basket`, `Study`) is inert: it writes its runs, and each
    run then succeeds or fails by itself. A walk-forward *decides* — it reads the training
    metrics, applies `metric`, and creates the test run from the answer. A fold whose training
    grid finished but whose choice could not be made (every point failed, or none traded) is a
    state no `backtests` row can express, and silence there would read as a fold that was never
    reached.

    ⚠️ **The folds share one set of strategies, and that falls out of a PR-203 decision.** A
    grid point's document contains no symbol and no dates, so the document for `period=9` is
    byte-identical in every fold; `_strategies_for` reuses the stored row. Six folds over a
    fifty-point grid is fifty strategies and three hundred runs, not three hundred strategies.
    """

    __tablename__ = "walk_forwards"

    id: Mapped[uuid.UUID] = _uuid_pk()

    # RESTRICT, like every other pointer at a study or a strategy: the walk-forward's whole
    # meaning is "this grid, tested blind", and a row whose grid had been deleted would state a
    # result about an experiment nobody could describe any more.
    study_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("studies.id", ondelete="RESTRICT"), nullable=False, index=True
    )

    folds: Mapped[int] = mapped_column(Integer, nullable=False)
    """How many train→test pairs the period is cut into.

    The knob with the sharpest trade-off in the whole feature, in both directions. Few folds
    give each test window enough bars for its result to mean something, but too few points to
    tell a stable parameter from one that wanders. Many folds show the wandering clearly and
    measure each fold on a sample so short that the wandering could be noise — which is the
    very failure the experiment was built to expose, reintroduced one level up.
    """

    train_multiple: Mapped[int] = mapped_column(Integer, nullable=False)
    """How many times longer the training window is than the test window that follows it.

    Stored rather than derived because it, `folds` and the number of candles are what produced
    every boundary in `walk_forward_folds`, and a boundary whose reasoning cannot be recovered
    is a boundary nobody can audit later.
    """

    anchored: Mapped[bool] = mapped_column(Boolean, nullable=False)
    """`True`: every fold trains on **all** history before its test window, so the training set
    grows. `False` (rolling): the training window is a fixed length that slides forward.

    Not a detail — the two ask different questions. Anchored asks *"does everything I know so
    far predict what comes next?"*, and uses more data each fold, so its later choices are the
    steadier ones. Rolling asks *"does the recent past predict the near future?"*, which is the
    honest question if a market's behaviour changes, and it keeps every fold's choice made from
    a sample of the same size — so the folds are comparable to each other, which anchored's are
    not.
    """

    metric: Mapped[SelectionMetric] = mapped_column(
        _enum(SelectionMetric, "selection_metric"), nullable=False
    )
    """The ranking that decides each fold's winner. See `SelectionMetric`."""

    status: Mapped[BacktestStatus] = mapped_column(
        _enum(BacktestStatus, "walk_forward_status"),
        nullable=False,
        default=BacktestStatus.QUEUED,
    )
    """Reusing the runs' state machine, deliberately: this row goes through exactly the same
    four states for exactly the same reasons, and a second vocabulary for `queued → running →
    done | failed` would be two words for one idea. The enum is stored as VARCHAR + CHECK
    (`native_enum=False`), so the constraint is this table's own and the two can diverge later
    without a migration touching both."""

    error: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[dt.datetime] = _created_at()
    started_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))

    fold_rows: Mapped[list[WalkForwardFold]] = relationship(
        back_populates="walk_forward",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="WalkForwardFold.index",
    )
    """Ordered in SQL, and the ordering is not cosmetic. A fold's number *is* its position in
    time, so folds arriving shuffled would put a later test window before an earlier one and
    the stitched out-of-sample result would be a different experiment. The same `now()`-per-
    transaction trap that shuffled a study's points applies here, and this is the fix that
    costs nothing: the fold carries its own index."""

    __table_args__ = (
        # One fold is a single train/test split — a useful thing, but not a walk-forward: it
        # cannot say whether a choice was stable, which is half of what this experiment reports.
        CheckConstraint("folds >= 2", name="folds_at_least_two"),
        CheckConstraint("train_multiple >= 1", name="train_at_least_as_long_as_test"),
        CheckConstraint("status <> 'failed' OR error IS NOT NULL", name="failed_needs_error"),
        CheckConstraint(
            "finished_at IS NULL OR started_at IS NOT NULL", name="finished_implies_started"
        ),
        CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at", name="finished_after_started"
        ),
    )


class WalkForwardFold(Base):
    """One train→test pair: the grid that was searched, and the single point that was tested.

    The row records **decisions and boundaries, never results.** Every number a reader wants
    from a fold — what the winner returned in training, what it returned out of sample, how
    many trades either took — is already stored on the runs, and copying any of it here would
    create a second place for it to be true.

    ⚠️ **The training window is not a column, and its absence is the design.** A fold's
    training grid *is* a `Study` — the same table `POST /studies` writes, over this fold's
    window — so the window is that study's own `date_from`/`date_to`. Writing it here as well
    would let a fold claim one window while the runs underneath it executed another. The test
    window has no such owner at write time (its run does not exist until a winner is known), so
    it does live here.
    """

    __tablename__ = "walk_forward_folds"

    # A composite primary key rather than a surrogate id, because the pair *is* the identity:
    # there is exactly one fold 3 of a given walk-forward, and no other row can be it. It also
    # makes the ordering above free, since the index is already part of the key.
    walk_forward_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("walk_forwards.id", ondelete="CASCADE"), primary_key=True
    )
    index: Mapped[int] = mapped_column(Integer, primary_key=True)

    study_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("studies.id", ondelete="RESTRICT"), nullable=False, unique=True
    )
    """The in-sample grid over this fold's training window — a full `Study`, readable through
    `GET /studies/{id}` with its own heatmap.

    Reused rather than reinvented because that heatmap is the evidence. Fold 1's heatmap beside
    fold 5's is what over-fitting *looks like*: if the bright region moves every fold, the grid
    was reading noise, and no summary number states it as plainly as the two pictures do.

    Unique: a study belongs to at most one fold, so the link cannot be quietly shared.
    """

    test_from: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    test_to: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    train_bars: Mapped[int] = mapped_column(Integer, nullable=False)
    test_bars: Mapped[int] = mapped_column(Integer, nullable=False)
    """How many candles the splitter counted into each window.

    Stored because the boundaries were cut **by bars and expressed as dates**, and only these
    two columns preserve the reasoning. A market has holidays, half-days and weekends, so equal
    stretches of calendar hold wildly unequal amounts of trading; cutting by time would give
    one fold twice the evidence of its neighbour while the row still read as an even split.
    These say what was actually counted, so a reader can check the split was even instead of
    trusting that it was.

    ⚠️ Planned, not observed. What each run *read* is on the run (`candles_seen`), and the two
    can honestly differ — a training window whose grid all failed reads nothing at all.
    """

    chosen_strategy_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("strategies.id", ondelete="RESTRICT")
    )
    """The point this fold's training grid selected — null until the fold has been decided.

    Null is also a **terminal** answer, not only a pending one: a fold whose every point failed,
    or whose every point took no trades, has no winner to name, and the walk-forward reports it
    as a fold that could not choose rather than inventing one. The two are told apart by the
    walk-forward's status, not by this column.
    """

    test_backtest_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("backtests.id", ondelete="SET NULL"), unique=True
    )
    """The out-of-sample run of the chosen point. The number the whole feature exists to
    produce, stored the same way every other run in the system is stored — as a `Backtest`,
    reproducible from its own strategy document, openable on the results screen like any other.

    SET NULL, not CASCADE, on the same principle as `backtests.basket_id`: deleting a run must
    not take the fold's record of what was decided with it.
    """

    walk_forward: Mapped[WalkForward] = relationship(back_populates="fold_rows")

    study: Mapped[Study] = relationship()
    """The training grid, reached as an object — this is where the fold's **training window**
    is read from, since the study's `date_from`/`date_to` are that window and this table
    deliberately does not copy them.

    No `back_populates`: a `Study` has no business knowing it is part of a fold. Studies exist
    on their own and predate this table, and a reverse link would have to be nullable on every
    one of them to describe a relationship most of them are not in.
    """

    __table_args__ = (
        CheckConstraint("index >= 0", name="index_non_negative"),
        CheckConstraint("test_to >= test_from", name="test_range"),
        # A window is cut by counting candles, so a window of none of them was never cut.
        CheckConstraint("train_bars > 0 AND test_bars > 0", name="windows_have_bars"),
        # A test run exists only because a choice was made. The reverse is allowed and happens:
        # the winner is recorded, then its run is created and executed.
        CheckConstraint(
            "test_backtest_id IS NULL OR chosen_strategy_id IS NOT NULL",
            name="test_run_implies_a_choice",
        ),
    )
