"""The relational model (sdd.md §5).

What lives here and what does not is ADR-05: Postgres holds *metadata and results*
— instruments, strategies, backtest runs, trades. It does not hold OHLCV. Years of
candles across dozens of symbols are a columnar problem, and they live in Parquet,
catalogued by the `datasets` table below.

Three rules run through every table:

* **Money is `NUMERIC`, never `float`** — see `base.py`.
* **Every timestamp is `TIMESTAMPTZ`** — a candle at "09:00" is meaningless without
  an offset, and a backtest that shifts by an hour when the server changes timezone
  is not a backtest.
* **The database enforces what it can.** A rule that only exists in Python is a rule
  the next maintenance script breaks. If a constraint is expressible in SQL, it is
  expressed in SQL — and there is a test that proves the constraint bites.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Computed,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Interval,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from tradeforge_db.base import MONEY, PRICE, RATIO, VOLUME, Base
from tradeforge_schema.models import TIMEFRAMES

# --------------------------------------------------------------------------- #
# Enumerations                                                                  #
# --------------------------------------------------------------------------- #
# Stored as VARCHAR + CHECK (`native_enum=False`), not as a Postgres ENUM type.
# A native enum is a schema object: adding `crypto` to it means ALTER TYPE, and
# *removing* a value is not supported at all — you rebuild the type and rewrite
# every column that uses it. A CHECK constraint is dropped and recreated in three
# lines, which is what makes these migrations honestly reversible. The cost is a
# few bytes per row over an enum's four; at this scale, nothing.


class AssetClass(StrEnum):
    FOREX = "forex"
    STOCK = "stock"
    INDEX = "index"
    FUTURE = "future"
    CRYPTO = "crypto"


class BacktestStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"


class Direction(StrEnum):
    LONG = "long"
    SHORT = "short"


class ExitReason(StrEnum):
    STOP_LOSS = "sl"
    TAKE_PROFIT = "tp"
    CONDITION = "condition"
    KILL = "kill"
    MANUAL = "manual"


def _enum(enum_type: type[StrEnum], name: str) -> Enum:
    # Two defaults here are traps, and both would have shipped silently.
    #
    # `create_constraint=True` is not the default in SQLAlchemy 2.0. Leave it off and
    # the column is a bare VARCHAR: any string at all gets in, and the enum exists only
    # in Python — precisely the "rule that lives in one place" failure this module is
    # written to avoid.
    #
    # `values_callable` is what makes the database store `'sl'` rather than
    # `'STOP_LOSS'`. By default SQLAlchemy persists the member *name*, not its value —
    # so the DSL, the API's JSON and the database would each spell the same exit reason
    # differently, and every query against a literal would quietly match nothing.
    return Enum(
        enum_type,
        name=name,
        native_enum=False,
        create_constraint=True,
        values_callable=lambda members: [member.value for member in members],
        length=16,
        validate_strings=True,
    )


# The set of legal timeframes is owned by the DSL, not by the database.
TIMEFRAME = String(4)
_TIMEFRAME_VALUES = ", ".join(f"'{tf}'" for tf in TIMEFRAMES)


def _timeframe_check() -> CheckConstraint:
    # The naming convention prefixes the table, so the same bare name yields
    # `ck_datasets_timeframe` and `ck_backtests_timeframe`.
    return CheckConstraint(f"timeframe IN ({_TIMEFRAME_VALUES})", name="timeframe")


def _uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID primary key, generated by the application.

    Used for everything the API addresses by id. Sequential integers would leak
    volume (`/backtests/1041` tells a competitor how many runs exist) and would
    force a round-trip to the database before a client can reference the row it is
    about to create. `trades` is the deliberate exception — see below.
    """
    return mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)


def _created_at() -> Mapped[dt.datetime]:
    # server_default, not a Python default: the database's clock is the one clock
    # every writer shares, whatever timezone the machine that inserted thinks it is in.
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


# --------------------------------------------------------------------------- #
# Instruments — what can be traded                                              #
# --------------------------------------------------------------------------- #


class Instrument(Base):
    """A tradable symbol and the numbers needed to price a position in it.

    `tick_size`, `tick_value` and `contract_size` are not decoration: they are how
    the engine converts a price move into money, and they differ by asset class.
    One tick of EURUSD on a standard lot is worth $1; one tick of AAPL is worth one
    cent per share. Get these wrong and every P&L in the system is wrong by a
    constant factor — which is exactly the kind of bug that looks like a great
    strategy. Populated for real by the collector from MT5 `symbol_info` (PR-102).
    """

    __tablename__ = "instruments"

    id: Mapped[uuid.UUID] = _uuid_pk()

    symbol: Mapped[str] = mapped_column(String(32), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    asset_class: Mapped[AssetClass] = mapped_column(
        _enum(AssetClass, "asset_class"), nullable=False
    )
    exchange: Mapped[str | None] = mapped_column(String(64))

    # Forex has a base and a quote currency (EUR/USD). A stock has only the currency
    # it settles in, so `currency_base` is nullable and `currency_quote` never is.
    currency_base: Mapped[str | None] = mapped_column(String(8))
    currency_quote: Mapped[str] = mapped_column(String(8), nullable=False)

    tick_size: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    tick_value: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    contract_size: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    digits: Mapped[int] = mapped_column(SmallInteger, nullable=False)

    created_at: Mapped[dt.datetime] = _created_at()
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # `passive_deletes="all"`: the database decides what a delete means, not the ORM.
    # By default SQLAlchemy "helpfully" NULLs out the children's foreign key before
    # deleting the parent — which would bypass the RESTRICT entirely if `instrument_id`
    # were nullable, silently orphaning every Parquet file this symbol catalogues. Told
    # to keep its hands off, it emits the DELETE and lets Postgres refuse.
    datasets: Mapped[list[Dataset]] = relationship(
        back_populates="instrument", passive_deletes="all"
    )

    __table_args__ = (
        # Zero or negative here would make position sizing divide by zero or flip
        # the sign of every trade. The database refuses before the engine ever sees it.
        CheckConstraint("tick_size > 0", name="tick_size_positive"),
        CheckConstraint("tick_value > 0", name="tick_value_positive"),
        CheckConstraint("contract_size > 0", name="contract_size_positive"),
        CheckConstraint("digits BETWEEN 0 AND 10", name="digits_range"),
    )


# --------------------------------------------------------------------------- #
# Datasets — the catalogue of what exists in Parquet                            #
# --------------------------------------------------------------------------- #


class Dataset(Base):
    """One (instrument, timeframe) coverage record pointing at Parquet on disk.

    The candles are not here; the *knowledge of which candles exist* is. That split
    is ADR-05, and it is what lets a backtest answer "do I have EURUSD H1 for 2021?"
    with an index lookup instead of opening files.

    One row per (instrument, timeframe): a re-run of the backfill updates the row it
    already owns rather than appending a second, contradictory account of the same
    range. That unique constraint is what makes the collector idempotent (PR-102).
    """

    __tablename__ = "datasets"

    id: Mapped[uuid.UUID] = _uuid_pk()

    # RESTRICT, not CASCADE: deleting a symbol must not silently orphan gigabytes of
    # Parquet. Whoever wants the instrument gone deals with its history first.
    instrument_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )
    timeframe: Mapped[str] = mapped_column(TIMEFRAME, nullable=False)

    date_from: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    date_to: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    candle_count: Mapped[int] = mapped_column(Integer, nullable=False)
    parquet_path: Mapped[str] = mapped_column(Text, nullable=False)
    collected_at: Mapped[dt.datetime] = _created_at()

    instrument: Mapped[Instrument] = relationship(back_populates="datasets")

    __table_args__ = (
        UniqueConstraint("instrument_id", "timeframe"),
        _timeframe_check(),
        CheckConstraint("date_to >= date_from", name="date_range"),
        CheckConstraint("candle_count >= 0", name="candle_count_non_negative"),
    )


# --------------------------------------------------------------------------- #
# Strategies — append-only                                                      #
# --------------------------------------------------------------------------- #


class Strategy(Base):
    """A saved strategy. **This table is append-only** (ADR-0010).

    A backtest is a claim about a specific strategy. If the strategy's definition
    can be edited in place, then every result ever produced becomes unexplainable:
    the row the run points at no longer describes the run. So editing is not an
    UPDATE — it is an INSERT of the next version, linked to its parent, and a
    trigger in the migration rejects UPDATE outright.

    `name`, `description` and `schema_version` are *generated columns*: Postgres
    derives them from the JSONB on write. They exist to be indexed and listed
    without parsing JSON, and being generated means they cannot disagree with the
    document they came from. The DSL stays the single source of truth, all the way
    down into the database.
    """

    __tablename__ = "strategies"

    id: Mapped[uuid.UUID] = _uuid_pk()

    # The DSL document, validated by `tradeforge_schema` before it ever gets here.
    definition: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)

    name: Mapped[str] = mapped_column(
        Text, Computed("definition ->> 'name'", persisted=True), nullable=False
    )
    description: Mapped[str | None] = mapped_column(
        Text, Computed("definition ->> 'description'", persisted=True)
    )
    schema_version: Mapped[str] = mapped_column(
        String(16), Computed("definition ->> 'schema_version'", persisted=True), nullable=False
    )

    version: Mapped[int] = mapped_column(Integer, nullable=False)
    parent_version_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("strategies.id", ondelete="RESTRICT")
    )

    created_at: Mapped[dt.datetime] = _created_at()

    parent: Mapped[Strategy | None] = relationship(remote_side="Strategy.id")

    __table_args__ = (
        # Two rows claiming to be "MA Cross v3" would make a backtest's provenance
        # ambiguous, which is the one thing this table exists to prevent.
        UniqueConstraint("name", "version"),
        CheckConstraint("version >= 1", name="version_positive"),
        # A first version has no parent; every later version must have one. Written
        # as an equivalence so both halves are enforced by the one constraint.
        CheckConstraint(
            "(version = 1) = (parent_version_id IS NULL)", name="lineage_starts_at_version_1"
        ),
    )


# --------------------------------------------------------------------------- #
# Backtests                                                                     #
# --------------------------------------------------------------------------- #


class Backtest(Base):
    """One run of one strategy version over one instrument and period.

    `engine_version` is stored alongside `strategy_id` on purpose. Reproducing a
    result needs both: the strategy says *what* was decided, the engine version says
    *how* it was executed. A fill-model bugfix six months from now changes the second
    without touching the first, and this column is what stops that from looking like
    the strategy silently got better.
    """

    __tablename__ = "backtests"

    id: Mapped[uuid.UUID] = _uuid_pk()

    strategy_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("strategies.id", ondelete="RESTRICT"), nullable=False
    )
    instrument_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )
    timeframe: Mapped[str] = mapped_column(TIMEFRAME, nullable=False)

    date_from: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    date_to: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    initial_capital: Mapped[Decimal] = mapped_column(MONEY, nullable=False)

    # The cost model is a plugged-in component (ADR-07), so its configuration is a
    # document, not a column. Storing it per run is what makes the run reproducible:
    # "the same backtest with a wider spread" must be a different, comparable row.
    cost_model: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)

    status: Mapped[BacktestStatus] = mapped_column(
        _enum(BacktestStatus, "backtest_status"),
        nullable=False,
        default=BacktestStatus.QUEUED,
    )
    error: Mapped[str | None] = mapped_column(Text)
    engine_version: Mapped[str] = mapped_column(String(32), nullable=False)

    created_at: Mapped[dt.datetime] = _created_at()
    started_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))

    # `passive_deletes=True` pairs with ON DELETE CASCADE: Postgres removes the children
    # in one statement. Without it, SQLAlchemy would load every trade of the run into
    # memory just to issue a DELETE per row — a backtest with 40 000 trades would take
    # 40 000 round trips to delete.
    metrics: Mapped[BacktestMetrics | None] = relationship(
        back_populates="backtest", cascade="all, delete-orphan", passive_deletes=True
    )
    trades: Mapped[list[Trade]] = relationship(
        back_populates="backtest", cascade="all, delete-orphan", passive_deletes=True
    )

    __table_args__ = (
        _timeframe_check(),
        CheckConstraint("date_to >= date_from", name="date_range"),
        CheckConstraint("initial_capital > 0", name="initial_capital_positive"),
        # A failed run that does not say why is a support ticket with no answer.
        CheckConstraint("status <> 'failed' OR error IS NOT NULL", name="failed_needs_error"),
        CheckConstraint(
            "finished_at IS NULL OR started_at IS NOT NULL", name="finished_implies_started"
        ),
        CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at", name="finished_after_started"
        ),
        # The worker polls for work by status; without this it seq-scans the table.
        Index("ix_backtests_status_created_at", "status", "created_at"),
    )


class BacktestMetrics(Base):
    """The summary of a finished run (sdd.md §5).

    The sign convention is enforced, not documented: `gross_profit >= 0`,
    `gross_loss <= 0`, and `net_profit` is exactly their sum. Every backtesting
    codebase eventually grows a bug where losses are added instead of subtracted
    because two functions disagreed about whether "loss" meant a negative number or
    a magnitude. Here the database settles it, and `NUMERIC` makes the equality check
    safe — the same CHECK on floats would fail on rounding alone.

    Nullable metrics are nullable for a reason: Sharpe over zero trades is not 0, it
    is undefined, and writing 0 there would quietly rank a strategy that never traded
    alongside one that broke even.
    """

    __tablename__ = "backtest_metrics"

    # PK *is* the FK: exactly one metrics row per backtest, enforced structurally
    # rather than by a unique index bolted on afterwards. CASCADE because metrics are
    # derived data — they have no meaning once the run they summarise is gone.
    backtest_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("backtests.id", ondelete="CASCADE"), primary_key=True
    )

    net_profit: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    gross_profit: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    gross_loss: Mapped[Decimal] = mapped_column(MONEY, nullable=False)

    total_trades: Mapped[int] = mapped_column(Integer, nullable=False)
    long_trades: Mapped[int] = mapped_column(Integer, nullable=False)
    short_trades: Mapped[int] = mapped_column(Integer, nullable=False)

    win_rate: Mapped[Decimal] = mapped_column(RATIO, nullable=False)
    payoff: Mapped[Decimal | None] = mapped_column(RATIO)
    profit_factor: Mapped[Decimal | None] = mapped_column(RATIO)
    expectancy: Mapped[Decimal | None] = mapped_column(MONEY)

    max_drawdown_abs: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    max_drawdown_pct: Mapped[Decimal] = mapped_column(RATIO, nullable=False)
    max_dd_duration_days: Mapped[int] = mapped_column(Integer, nullable=False)

    sharpe: Mapped[Decimal | None] = mapped_column(RATIO)
    sortino: Mapped[Decimal | None] = mapped_column(RATIO)
    cagr: Mapped[Decimal | None] = mapped_column(RATIO)

    avg_trade_duration: Mapped[dt.timedelta | None] = mapped_column(Interval)

    # The equity curve is a time series, read whole and never queried by element —
    # a JSONB array, not ten thousand rows in a table nobody joins against.
    equity_curve: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)

    backtest: Mapped[Backtest] = relationship(back_populates="metrics")

    __table_args__ = (
        CheckConstraint("gross_profit >= 0", name="gross_profit_sign"),
        CheckConstraint("gross_loss <= 0", name="gross_loss_sign"),
        CheckConstraint("net_profit = gross_profit + gross_loss", name="net_profit_balances"),
        CheckConstraint("total_trades = long_trades + short_trades", name="trade_counts_balance"),
        CheckConstraint("total_trades >= 0", name="total_trades_non_negative"),
        CheckConstraint("win_rate BETWEEN 0 AND 1", name="win_rate_is_a_fraction"),
        CheckConstraint("max_drawdown_abs >= 0", name="max_drawdown_abs_non_negative"),
        CheckConstraint("max_drawdown_pct BETWEEN 0 AND 1", name="max_drawdown_pct_is_a_fraction"),
        CheckConstraint("max_dd_duration_days >= 0", name="max_dd_duration_non_negative"),
    )


# --------------------------------------------------------------------------- #
# Trades                                                                        #
# --------------------------------------------------------------------------- #


class Trade(Base):
    """One round trip, with the indicator snapshot that justified the entry.

    `context` is the column this table is really for. It stores what the indicators
    read at the moment of entry, which is what will later answer "does this strategy
    only work when ADX > 25?" — and it is the training material for the phase-3 LLM
    analysis. Recomputing it afterwards would mean re-running the engine and hoping
    nothing changed; capturing it at the entry costs nothing.

    Unlike every other table here, the primary key is a BIGINT, not a UUID. Trades
    are high-volume and are never addressed individually by a client — they are read
    in bulk by `backtest_id`. A sequential key keeps that index compact and its
    inserts append-only at the right edge of the B-tree, which a random UUID does not.

    `backtest_id` is NOT NULL today. Phase 2 adds live sessions and relaxes this into
    "exactly one of backtest_id / live_session_id", which is an honest migration then
    — as opposed to a nullable foreign key now, pointing at a table that does not exist.
    """

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    backtest_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("backtests.id", ondelete="CASCADE"), nullable=False
    )
    instrument_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )

    direction: Mapped[Direction] = mapped_column(_enum(Direction, "direction"), nullable=False)

    entry_time: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    volume: Mapped[Decimal] = mapped_column(VOLUME, nullable=False)

    # An open position has no exit yet. The CHECKs below keep the four exit columns
    # from ever telling half a story — a trade with an exit price but no exit time is
    # not a trade, it is a bug that would land in the metrics as free money.
    exit_time: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    exit_price: Mapped[Decimal | None] = mapped_column(PRICE)
    exit_reason: Mapped[ExitReason | None] = mapped_column(_enum(ExitReason, "exit_reason"))

    stop_loss: Mapped[Decimal | None] = mapped_column(PRICE)
    take_profit: Mapped[Decimal | None] = mapped_column(PRICE)

    gross_pnl: Mapped[Decimal | None] = mapped_column(MONEY)
    costs: Mapped[Decimal | None] = mapped_column(MONEY)
    net_pnl: Mapped[Decimal | None] = mapped_column(MONEY)
    r_multiple: Mapped[Decimal | None] = mapped_column(RATIO)

    context: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    backtest: Mapped[Backtest] = relationship(back_populates="trades")

    __table_args__ = (
        CheckConstraint("entry_price > 0", name="entry_price_positive"),
        CheckConstraint("exit_price IS NULL OR exit_price > 0", name="exit_price_positive"),
        CheckConstraint("volume > 0", name="volume_positive"),
        # Closed means closed: all four exit columns arrive together or none do.
        CheckConstraint(
            "(exit_time IS NULL) = (exit_price IS NULL)"
            " AND (exit_time IS NULL) = (exit_reason IS NULL)"
            " AND (exit_time IS NULL) = (net_pnl IS NULL)",
            name="exit_is_all_or_nothing",
        ),
        CheckConstraint("exit_time IS NULL OR exit_time >= entry_time", name="exit_after_entry"),
        # Costs are a magnitude, and net is gross minus them. Stating it here means no
        # two call sites can disagree about the sign — the same trap as gross_loss above.
        CheckConstraint("costs IS NULL OR costs >= 0", name="costs_non_negative"),
        CheckConstraint("net_pnl IS NULL OR net_pnl = gross_pnl - costs", name="net_pnl_balances"),
        Index("ix_trades_backtest_id_entry_time", "backtest_id", "entry_time"),
    )
